version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - redis
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/mydb
      - REDIS_HOST=redis

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
